### ISSUE TITLE
Jumping to begin of next row on keyboard

### ISSUE THREAD

**Issue by s0i37** [hashcat/kwprocessor#20]
Hello.
I can't generate character combination like `qweasd`:
![temp](https://user-images.githubusercontent.com/22872513/73279967-ad709280-420f-11ea-8365-a74bf9b4043d.png)
It is very popular keywalk, which presume jumping back to bottom row on keyboard
It means 3 directions (route 212) and some distance between keys more than 1, but nothing:
```
./kwp -0 -x 6 basechars/tiny.base keymaps/en-us.keymap routes/2-to-10-max-3-direction-changes.route|grep qweasd
```

**Comment by jsteube** [comment]
That's not the way it is supposed to work. Instead, you want it to generate only "qwer" and "asdf" using a simple route. The "jumping" is created by using hashcat in -a 1 mode (or combinator.bin from hashcat-utils). You will also get the benefit of full GPU acceleration even for fast hashes.

```
$ ./kwp basechars/full.base keymaps/en-us.keymap routes/2-to-10-max-2-direction-changes-combinator.route > wl.txt
$ echo -n qwerasdf | md5sum
350c9d901b7f1c73a481e240ec1b7c0b  -
$ ./hashcat --quiet 350c9d901b7f1c73a481e240ec1b7c0b -a 1 wl.txt wl.txt 
350c9d901b7f1c73a481e240ec1b7c0b:qwerasdf
$
```
