### ISSUE TITLE
Segfault with 8bits keymaps

### ISSUE THREAD

**Issue by Hydraze** [hashcat/kwprocessor#4]
While working on the french 8 bits keymap, I noticed a segfault during my tests. After thinking that I messed up my keymap file (again), I noticed a similar issue with the de.keymap (even on a clean repository).

On the de.keymap I get the following matrix:

route / base | tiny.base | full.base
---------------|------------|-------------
3x3.route | OK | Segfault
2-to-10.route | OK | Segfault
2-to-16.route | Segfault | Segfault

(I get a different matrix on my reworked 8bits french keymap so I still might have messed up.)

According to gdb, the segfault is occuring on line 519:
const int c = cs->map[m];

**Comment by jsteube** [comment]
Please retry with the new patch and close the issue if fixed
